/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2022-12-09 06:52:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.sub;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class sub1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/hth/pro04/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pro04/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/hth/pro04/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pro04/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1668995163779L));
    _jspx_dependants.put("jar:file:/D:/hth/pro04/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pro04/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"https://www.ottogi.co.kr/css/style.css\" type=\"text/css\" rel=\"stylesheet\" media=\"screen,projection\">\r\n");
      out.write("<style>\r\n");
      out.write("  .section { width:1200px; height: 4500px; margin-left: 400px; }\r\n");
      out.write("</style>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/head.jsp", out, false);
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/header.jsp", out, false);
      out.write("\r\n");
      out.write("<div class=\"section\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"tit_content\">\r\n");
      out.write("                <h2 class=\"header center titbul\">창업주 풍림 함태호 생애</h2>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"hamtaiho01\">\r\n");
      out.write("                <div class=\"left\">\r\n");
      out.write("                    <h3>풍림 함태호 명예회장</h3>\r\n");
      out.write("                    <h4>(1930 - 2016)</h4>\r\n");
      out.write("                    <p>오뚜기의 창업주인 고(故) 함태호 명예회장은 1930년 함경남도 원산에서 태어났습니다.</p>\r\n");
      out.write("                    <p>부친 함형준씨와 모친 이덕발 씨의 장남으로 태어난 소년 함태호는 경기고등학교에 입학하였고, 재학중에 1950년 한국전쟁이 발발하자 피난 대신 자원 입대했습니다. 자신의 안위보다 나라사랑이 깊었던 함태호 명예회장은 한국전쟁 임시군사교육학교인 육군종합학교를 거쳐 소위로 임관하여 1957년까지 근무하였습니다.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"right\"><img src=\"https://www.ottogi.co.kr/images/content/img/hamtaiho_01_2.jpg\" alt=\"\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"hamtaiho02\">\r\n");
      out.write("                <h3>군문(軍門)을 나와 경영을 배우다</h3>\r\n");
      out.write("                <div class=\"left\">\r\n");
      out.write("                    <p>군인으로 국가에 기여하겠다는 충심으로 전선에서 사선을 넘나들었던 함태호 명예회장은 전쟁이 끝나고 30대를 앞두게 되자, 무기를 들고 나라를 지키는 일도 중요하지만 헐벗은 국가경제와 굶주린 국민들을 위해 식품산업을 일으키는 것도 절실하다고 느꼈습니다.<br>\r\n");
      out.write("                    소령으로 군을 전역한 함태호 명예회장은 1959년 조흥화학에 입사해 사회생활을 시작했습니다. 이후 10년 동안 함태호 명예회장은 선친 밑에서 경영수업을 받으며 기획에서 영업, 재무 등 두루 경험을 쌓는 한편, 경영인으로서의 소양을 쌓고자 홍익대학교 상학과를 나와 1968년 연세대학교 경영대학원에서 석사과정을 이수했습니다. 혹독하게 쌓아온 이 시기의 경험이 경영자 함태호를 만든 힘이었습니다. </p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"right\">\r\n");
      out.write("                    <p>조흥화학 입사 10년 만에 함태호 명예회장은 독립을 꿈꾸었습니다. 아버지의 뒤를 잇는 것도 중요하지만, 자신의 길을 홀로 개척하는 것이 더욱 의미 있는 일이라 여겼기 때문입니다. 함태호 명예회장이 고심해 선택한 분야는 식품사업이었습니다. 인공 감미료와 식품첨가물을 만드는 조흥화학의 업무를 수행하면서 식품사업에 대한 이해가 깊었고, 직접 식품사업에 뛰어들어 국민들의 식생활 개선에 기여하고자 하는 열망도 컸습니다. 결심이 굳어지자 함태호 명예회장은 선친에게 포부를 밝혔고, 선친의 독립에 대한 전폭적인 지지를 받으며 조흥화학을 떠나 홀로서기에 나섰습니다.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"hamtaiho03\">\r\n");
      out.write("                <div class=\"left\">\r\n");
      out.write("                    <img src=\"https://www.ottogi.co.kr/images/content/img/hamtaiho_02.jpg\" class=\"ham_img\" alt=\"(주) 오뚜기 창업주 함태호 명예회장(왼쪽 세번째)의 조흥화학 재직시절 모습\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"right\">\r\n");
      out.write("                    <img src=\"	https://www.ottogi.co.kr/images/content/img/hamtaiho_02_2.jpg\" class=\"ham_img\" alt=\"(주) 오뚜기 창업주 함태호 명예회장(왼쪽 세번째)의 조흥화학 재직시절 모습\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"hamtaiho04\">\r\n");
      out.write("                <h3>준비된 경영인이 만든 ‘카레와 마요네스의 선풍’</h3>\r\n");
      out.write("                <div class=\"left\">\r\n");
      out.write("                    <p>마흔에 접어든 1969년 함태호는 풍림상사를 설립하고, 영등포 문래동에 작은 공장까지 마련했습니다. 오랜 준비가 있었기에 진행은 일사천리였고, 단 몇 개월의 준비 끝에 1969년 5월 5일 첫 제품을 시장에 내놓았습니다. 반세기가 넘도록 정상의 자리를 지킨 ‘오뚜기 카레’가 세상에 첫 선을 보이는 순간이었습니다. 누구도 생각지 않았던 인도의 커리가 일본을 거쳐 한국에서 우리만의 새로운 식품으로 태어난 것이었습니다.<br>\r\n");
      out.write("이후 함태호 명예회장과 오뚜기의 행보는 거침이 없었습니다. 스프, 케챂, 마요네스, 식초를 연이어 내놓으며 우리나라 식단에 혁신을 이끌었습니다. 제품을 내놓는 대로 시장의 베스트셀러가 되었고, 오뚜기 3분 카레로 대표되는 즉석식품은 오뚜기를 다시금 시장에 깊은 인상을 남기는 계기가 되었습니다.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"right\">\r\n");
      out.write("                    <p>1980년대 후반에는 청보식품을 인수하며 라면사업에 진출하고, 참치, 즉석밥 시장으로 지평을 넓히며 식품기업으로서의 입지를 굳건히 했습니다. 설립 10년 만인 1979년 1백억 원, 1988년에는 1천억 원의 매출을 기록하며 중견기업으로 성장할 토대를 확고히 한 ㈜오뚜기는 성장의 역사를 이어오며 2017년에는 매출 2조 원 시대를 열었습니다.<br> \r\n");
      out.write("㈜오뚜기는 설립 이후 반세기에 다다를 동안 한 번도 마이너스 성장을 기록하지 않고 앞으로만 내달렸습니다. 출시 제품과 수준도 다양해지고 깊어졌습니다. 이제 오뚜기의 제품이 없는 주방과 식단은 찾아보기 힘들 정도로 생활기업이자 국민기업으로 성장한 것입니다.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"hamtaiho05\">\r\n");
      out.write("                <div class=\"left\">\r\n");
      out.write("                    <img src=\"	https://www.ottogi.co.kr/images/content/img/hamtaiho_03.jpg\" class=\"ham_img\" alt=\"문래동 창립공장\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"right\">\r\n");
      out.write("                    <img src=\"	https://www.ottogi.co.kr/images/content/img/hamtaiho_04.jpg\" class=\"ham_img\" alt=\"창립제품 오뚜기 즉석카레 (1969년 5월 5일)\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <h5>문래동 창립공장과 창립제품 오뚜기 즉석카레 (1969년 5월 5일)</h5>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"hamtaiho06\">\r\n");
      out.write("                <div class=\"left\">\r\n");
      out.write("                    <h3>부전상립의 오뚜기 정신</h3>\r\n");
      out.write("                    <p>㈜오뚜기와 함태호 명예회장에게 오뚜기는 넘어져도 다시 일어나겠다는 것이 아니라, 결코 넘어지지 않고 항상 서 있는 부전상립(不轉常立) 입니다.<br>\r\n");
      out.write("1980년대 10여 년에 걸친 다국적기업과의 경쟁에서 우리 시장을 지켜내며 승리한 사례에서 기업가로서의 강인함을 엿볼 수 있었으며, 영업사원이 거래처를 직접 방문해 진열을 돕고 소비자와 직접 대면하는 루트세일(Route Sale)을 국내 최초로 실시해 시장을 점령, 우리나라 최초의 시식판매 및 판매여사원 제도를 도입, 국내 최초의 파격적인 차량 광고마케팅 등을 통해 고객의 마음을 움직이는 등 창의적이고 진취적인 정신을 발견할 수 있습니다. 함태호 명예회장은 치열한 시장경쟁 속에서도 직원들을 가족처럼 대하면서 사기를 높이고, 협력업체의 이익을 보장하는 동반성장을 통해 함께 싸우고 견뎌냈습니다.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"right\">\r\n");
      out.write("                    <img src=\"	https://www.ottogi.co.kr/images/content/img/hamtaiho_05.jpg\" class=\"ham_img\" alt=\"시장점유율 확대를 위해 전국을 달렸던 영업차량\">\r\n");
      out.write("                    <h5>시장점유율 확대를 위해 전국을 달렸던 영업차량</h5>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"hamtaiho07\">\r\n");
      out.write("                <div class=\"left\">\r\n");
      out.write("                    <img src=\"	https://www.ottogi.co.kr/images/content/img/hamtaiho_06.jpg\" class=\"ham_img\" alt=\"오뚜기 대풍공장에 계양된 가로 10.5m, 세로 7m의 대형 태극기\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"right\">\r\n");
      out.write("                    <h3>투철한 국가관, 따뜻한 나눔</h3>\r\n");
      out.write("                    <p>오뚝이 모양에 어린이의 밝은 미소를 짓는 로고는 우리 시대 가장 유명한 디자인이라 해도 과언이 아닙니다. 그러나 기업인이자 자연인으로서의 함태호 명예회장은 그림자 같은 경영인이었습니다. 제품과 브랜드는 내세워도 경영자는 항상 한 발 물러서 있었습니다. 왼손이 하는 일을 오른손이 모르게 하는 일이 그에게는 너무도 익숙한 삶이었기 때문입니다.\r\n");
      out.write("함태호 명예회장은 항상 가슴 속에 나라가 우선이라는 마음을 품고 살았습니다. 전국의 오뚜기 공장에 태극기를 게양하고 있으며 오뚜기 사내 월례조회와 행사에서는 항상 애국가를 4절까지 제창합니다. 애국가를 부르는 가운데 기업이 국가에 기여할 수 있는 각오를 다지는 것으로, 오늘날의 기업에서 찾아보기 힘든 풍경이지만 나보다 우리, 우리보다 국가를 우선하는 함태호 명예회장 정신을 엿볼 수 있는 장면입니다. </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"hamtaiho08\">\r\n");
      out.write("                <div class=\"left\">\r\n");
      out.write("                    <p>이러한 투철한 국가관에 진정성을 더한 것은 함태호 명예회장의 따뜻한 나눔의 실천입니다. 이미 기업 초창기부터 회사 차원에서 지역사회에 공헌하고 어려운 이웃을 도와 왔던 함태호 명예회장은 1996년 (재)오뚜기 재단을 설립해 장학사업을 전개해 50억 원의 장학금을 800명의 대학생에 지급했으며, 돌아가신 이후에도 지속적인 사업을 전개해 나가 현재 1천여 명이 넘는 학생들에게 70여억 원의 장학금을 전달하였습니다.<br>\r\n");
      out.write("2012년에는 장애인 복지법인 밀알복지재단에 후원 사업을 시작했습니다. 단순한 후원이 아닌 굿윌스토어라는 자립 프로그램을 통해 일자리를 제공해 스스로 독립할 수 있는 환경을 제공한 것입니다. 2021년 후원 10주년을 맞이한 오뚜기의 장애인 후원 사업은 계속 이어지고 있습니다. </p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"right\">\r\n");
      out.write("                    <p>함태호 명예회장의 삶에서 떼어 놓을 수 없는 것이 심장병 어린이 후원사업입니다. 1992년 많은 수술비를 감당하지 못해 살릴 수 있는 생명이 고통받는다는 소식을 접한 이후 한국심장재단을 통해 선천성 심장병 어린이 후원을 시작했습니다. 처음 매월 5명을 시작으로 현재는 매월 22명의 어린이가 ㈜오뚜기의 후원을 받아 새 생명을 얻고 있습니다. 2016년 9월 함태호 명예회장이 영면에 들기 직전까지 그가 품에 안은 어린이는 4,265명이었고, 이후로도 함태호 명예회장의 아름다운 유지는 오뚜기에 의해 이어지고 있습니다. 새롭게 생명을 얻는 어린이들이 고사리 손으로 적어 보낸 편지를 그 어떤 명예보다도 소중히 여겼던 함태호 명예회장의 빈소에 유독 어린이와 청년들이 많았던 것도 오랜 나눔의 인연 때문이었습니다. </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"hamtaiho09\">\r\n");
      out.write("                <div class=\"left\">\r\n");
      out.write("                    <img src=\"	https://www.ottogi.co.kr/images/content/img/hamtaiho_07.jpg\" class=\"ham_img\" alt=\"2001년 새 생명 탄생 1,000명 기념행사, 2007년 새 생명 탄생 2,000명 기념행사\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"right\">\r\n");
      out.write("                    <img src=\"	https://www.ottogi.co.kr/images/content/img/hamtaiho_08.jpg\" class=\"ham_img\" alt=\"2011년 새 생명 탄생 3,000명 기념행사, 2015년 새 생명 탄생 4,000명 기념행사\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <h5>(좌측부터) 2001년 새 생명 탄생 1,000명 기념행사, 2007년 새 생명 탄생 2,000명 기념행사, <br>\r\n");
      out.write("2011년 새 생명 탄생 3,000명 기념행사, 2015년 새 생명 탄생 4,000명 기념행사</h5>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"hamtaiho10\">\r\n");
      out.write("                <div class=\"left\">2016년 9월 12일, 87세를 일기로 영면한 오뚜기 창업주 함태호 명예회장\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"right\">\r\n");
      out.write("                    <h3>가치 있는 삶</h3>\r\n");
      out.write("                    <p>함태호 명예회장은 기업인으로 생애 대부분을 보내며 ㈜오뚜기를 우리나라를 대표하는 식품기업으로 일궜습니다. 이는 새로운 맛을 찾고, 창조하며 세상이 음미하도록 하는 일에 몰두한 결과물이었습니다. 우리의 식탁을 풍성하게 하겠다는 함태호 명예회장의 생각은 설립 초부터 굳건히 견지한 오뚜기의 기업이념인 ‘인류의 식생활 향상과 건강에 이바지하는 기업, 맛과 품질을 가장 소중히 생각하고 행동하는 기업, 소비자에게 맛과 품질을 책임지는 기업, 인류에게 필요로 하는 기업’에 잘 나타나 있습니다. 그리고 함태호 명예회장의 삶은 오뚜기의 기업이념이 생동하는 실천임을 확인시켜 주었습니다. </p>\r\n");
      out.write("                    <p>품질제일주의로 한 평생을 살아오며 국내 식품산업의 최초의 제품, 제품의 대중화를 이룩해 냈던 함태호 명예회장은 2016년 9월 12일 87세를 일기로 영면에 들었습니다. 함께 사는 세상을 꿈꾸는 존경 받는 기업인이자 주머니를 훌훌 털어 남과 나눌 수 있는 우리 시대의 어른은 곁을 떠나갔지만, “인류에 필요한 기업이 되었으면 좋겠다. 그것이 우리들의 꿈이고, 목표고 바람이다” 라고 말했던 그의 뜻은 늘 변하지 않는 꿈, 한결 같은 바람을 가지고 오뚜기에 계승되고 있습니다.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/sub/sub1.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path1");
      // /WEB-INF/views/sub/sub1.jsp(6,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/sub/sub1.jsp(6,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
