/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2022-12-09 07:46:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.sub;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class sub6_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/hth/pro04/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pro04/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/hth/pro04/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pro04/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1668995163779L));
    _jspx_dependants.put("jar:file:/D:/hth/pro04/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pro04/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("    <link href=\"https://www.ottogi.co.kr/css/style.css\" type=\"text/css\" rel=\"stylesheet\" media=\"screen,projection\">\r\n");
      out.write("    <link href=\"https://www.ottogi.co.kr/css/materialize.css\" type=\"text/css\" rel=\"stylesheet\" media=\"screen,projection\">\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/head.jsp", out, false);
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/header.jsp", out, false);
      out.write("\r\n");
      out.write("    <div class=\"section\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"tit_content\">\r\n");
      out.write("                <h2 class=\"header center titbul \">신제품 소개</h2>\r\n");
      out.write("                <p>오뚜기에서 새롭게 선보이는 신제품을 소개해 드립니다</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"container fix newGoods mt50\">\r\n");
      out.write("                <div class=\"left\">\r\n");
      out.write("                    <div class=\"bx-wrapper\" style=\"max-width: 100%;\"><div class=\"bx-viewport\" style=\"width: 100%; overflow: hidden; position: relative; height: 600px;\"><ul class=\"bxslider3 fix\" style=\"width: 515%; position: relative; transition-duration: 0s; transform: translate3d(-600px, 0px, 0px);\"><li onclick=\"location.href=&#39;https://ottogi.co.kr/product/product_view.asp?page=2&amp;hcode=&amp;mcode=&amp;stxt=&amp;orderby=NEW&amp;idx=2424&#39;\" style=\"float: left; list-style: none; position: relative; width: 600px;\" class=\"bx-clone\"><a href=\"https://www.ottogi.co.kr/product/product_list.asp#!\" tabindex=\"-1\">\r\n");
      out.write("                    <img src=\"	https://www.ottogi.co.kr/pds/upfile/2022-10-13_858980330[2].jpg\" alt=\"오즈키친 치킨마크니\"><span class=\"flag\">NEW</span></a></li>\r\n");
      out.write("                        \r\n");
      out.write("                        <li onclick=\"location.href='https://ottogi.co.kr/product/product_view.asp?page=1&amp;hcode=&amp;mcode=&amp;stxt=&amp;orderby=NEW&amp;idx=2431&#39;'\" style=\"float: left; list-style: none; position: relative; width: 600px;\"><a href=\"https://www.ottogi.co.kr/product/product_list.asp#!\"><img src=\"https://www.ottogi.co.kr/pds/upfile/2022-10-13_858980330[2].jpg\" alt=\"대전식 쇠고기무국\"><span class=\"flag\">NEW</span></a></li><!-- 2017-06-06 a 태그 추가 -->\r\n");
      out.write("                        \r\n");
      out.write("                        <li onclick=\"location.href='https://ottogi.co.kr/product/product_view.asp?page=2&amp;hcode=&amp;mcode=&amp;stxt=&amp;orderby=NEW&amp;idx=2418&#39;'\" style=\"float: left; list-style: none; position: relative; width: 600px;\"><a href=\"https://www.ottogi.co.kr/product/product_list.asp#!\"><img src=\"\" alt=\"컵누들 로제맛\"><span class=\"flag\">NEW</span></a></li><!-- 2017-06-06 a 태그 추가 -->\r\n");
      out.write("                        \r\n");
      out.write("                        <li onclick=\"location.href='https://ottogi.co.kr/product/product_view.asp?page=2&amp;hcode=&amp;mcode=&amp;stxt=&amp;orderby=NEW&amp;idx=2424&#39;'\" style=\"float: left; list-style: none; position: relative; width: 600px;\"><a href=\"https://www.ottogi.co.kr/product/product_list.asp#!\"><img src=\"\" alt=\"오즈키친 치킨마크니\"><span class=\"flag\">NEW</span></a></li><!-- 2017-06-06 a 태그 추가 -->\r\n");
      out.write("                        \r\n");
      out.write("                    <li onclick=\"location.href='https://ottogi.co.kr/product/product_view.asp?page=1&amp;hcode=&amp;mcode=&amp;stxt=&amp;orderby=NEW&amp;idx=2431&#39;'\" style=\"float: left; list-style: none; position: relative; width: 600px;\" class=\"bx-clone\"><a href=\"https://www.ottogi.co.kr/product/product_list.asp#!\" tabindex=\"-1\"><img src=\"\" alt=\"대전식 쇠고기무국\"><span class=\"flag\">NEW</span></a></li></ul></div><div style=\"display: none;\" class=\"bx-controls bx-has-pager bx-has-controls-direction bx-has-controls-auto\"><div class=\"bx-pager bx-default-pager\"><div class=\"bx-pager-item\"><a href=\"https://www.ottogi.co.kr/product/product_list.asp#none\" data-slide-index=\"0\" class=\"bx-pager-link active\">1</a></div><div class=\"bx-pager-item\"><a href=\"https://www.ottogi.co.kr/product/product_list.asp#none\" data-slide-index=\"1\" class=\"bx-pager-link\">2</a></div><div class=\"bx-pager-item\"><a href=\"https://www.ottogi.co.kr/product/product_list.asp#none\" data-slide-index=\"2\" class=\"bx-pager-link\">3</a></div></div><div class=\"bx-controls-direction\"><a class=\"bx-prev\" href=\"https://www.ottogi.co.kr/product/product_list.asp#none\">Prev</a><a class=\"bx-next\" href=\"https://www.ottogi.co.kr/product/product_list.asp#none\">Next</a></div><div class=\"bx-controls-auto\"><div class=\"bx-controls-auto-item\"><a class=\"bx-start active\" href=\"https://www.ottogi.co.kr/product/product_list.asp\">Start</a></div><div class=\"bx-controls-auto-item\"><a class=\"bx-stop\" href=\"https://www.ottogi.co.kr/product/product_list.asp\">Stop</a></div></div></div></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"right newList newList2\">\r\n");
      out.write("                    <ul class=\"row\">\r\n");
      out.write("                        \r\n");
      out.write("                        <li class=\"col\" onclick=\"location.href=&#39;product_view.asp?page=1&amp;hcode=0&amp;mcode=0&amp;stxt=&amp;orderby=BEST&amp;idx=2447&#39;\">\r\n");
      out.write("                            <div class=\"card no-margin\">\r\n");
      out.write("                                <div class=\"card-image\">\r\n");
      out.write("                                    <!-- 2017-06-04 a 태그 추가 -->\r\n");
      out.write("                                    <a href=\"https://www.ottogi.co.kr/product/product_list.asp#none\">\r\n");
      out.write("                                        <img class=\"activator\" src=\"https://www.ottogi.co.kr/pds/product/2022-11-25_894683539[2].jpg\" alt=\"헬로베지_건강한버섯솥밥 402G냉장/냉동식품냉동밥\">\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"card-content\">\r\n");
      out.write("                                    <span class=\"activator grey-text text-lighten-5 ellip\">헬로베지_건강한버섯솥밥 402G</span>\r\n");
      out.write("                                    <p>냉장/냉동식품 &gt; 냉동밥</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <span class=\"flag\">NEW</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>	\r\n");
      out.write("                        \r\n");
      out.write("                        <li class=\"col\" onclick=\"location.href=&#39;product_view.asp?page=1&amp;hcode=0&amp;mcode=0&amp;stxt=&amp;orderby=BEST&amp;idx=2446&#39;\">\r\n");
      out.write("                            <div class=\"card no-margin\">\r\n");
      out.write("                                <div class=\"card-image\">\r\n");
      out.write("                                    <!-- 2017-06-04 a 태그 추가 -->\r\n");
      out.write("                                    <a href=\"https://www.ottogi.co.kr/product/product_list.asp#none\">\r\n");
      out.write("                                        <img class=\"activator\" src=\"https://www.ottogi.co.kr/pds/product/2022-11-25_894683539.jpg\" alt=\"헬로베지_건강한나물솥밥 408G냉장/냉동식품냉동밥\">\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"card-content\">\r\n");
      out.write("                                    <span class=\"activator grey-text text-lighten-5 ellip\">헬로베지_건강한나물솥밥 408G</span>\r\n");
      out.write("                                    <p>냉장/냉동식품 &gt; 냉동밥</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <span class=\"flag\">NEW</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>	\r\n");
      out.write("                        \r\n");
      out.write("                        <li class=\"col\" onclick=\"location.href=&#39;product_view.asp?page=1&amp;hcode=0&amp;mcode=0&amp;stxt=&amp;orderby=BEST&amp;idx=2445&#39;\">\r\n");
      out.write("                            <div class=\"card no-margin\">\r\n");
      out.write("                                <div class=\"card-image\">\r\n");
      out.write("                                    <!-- 2017-06-04 a 태그 추가 -->\r\n");
      out.write("                                    <a href=\"https://www.ottogi.co.kr/product/product_list.asp#none\">\r\n");
      out.write("                                        <img class=\"activator\" src=\"https://www.ottogi.co.kr/pds/product/2022-11-24_894670281[2].jpg\" alt=\"뿌셔뿌셔 달고나맛라면스낵류뿌셔뿌셔\">\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"card-content\">\r\n");
      out.write("                                    <span class=\"activator grey-text text-lighten-5 ellip\">뿌셔뿌셔 달고나맛</span>\r\n");
      out.write("                                    <p>라면스낵류 &gt; 뿌셔뿌셔</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <span class=\"flag\">NEW</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>	\r\n");
      out.write("                        \r\n");
      out.write("                        <li class=\"col\" onclick=\"location.href=&#39;product_view.asp?page=1&amp;hcode=0&amp;mcode=0&amp;stxt=&amp;orderby=BEST&amp;idx=2443&#39;\">\r\n");
      out.write("                            <div class=\"card no-margin\">\r\n");
      out.write("                                <div class=\"card-image\">\r\n");
      out.write("                                    <!-- 2017-06-04 a 태그 추가 -->\r\n");
      out.write("                                    <a href=\"https://www.ottogi.co.kr/product/product_list.asp#none\">\r\n");
      out.write("                                        <img class=\"activator\" src=\"	https://www.ottogi.co.kr/pds/product/2022-11-11_690210940.jpg\" alt=\"맥앤치즈볼냉장/냉동식품조리냉동류\">\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"card-content\">\r\n");
      out.write("                                    <span class=\"activator grey-text text-lighten-5 ellip\">맥앤치즈볼</span>\r\n");
      out.write("                                    <p>냉장/냉동식품 &gt; 조리냉동류</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <span class=\"flag\">NEW</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>	\r\n");
      out.write("                                \r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
