/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2022-12-09 06:15:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/hth/pro04/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pro04/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/hth/pro04/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pro04/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1668995163779L));
    _jspx_dependants.put("jar:file:/D:/hth/pro04/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pro04/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("	<title>Home</title>\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./include/head.jsp", out, false);
      out.write("\n");
      out.write("<style>\n");
      out.write("$white: #fefefe;\n");
      out.write("\n");
      out.write("body {\n");
      out.write("  padding: 2rem 1rem;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".docs-example-orbit-slide {\n");
      out.write("  padding: 2rem 4rem;\n");
      out.write("  color: $white;\n");
      out.write("\n");
      out.write("  .orbit-slide:nth-of-type(1) & {\n");
      out.write("    background: dodgerblue;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  .orbit-slide:nth-of-type(2) & {\n");
      out.write("    background: rebeccapurple;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  .orbit-slide:nth-of-type(3) & {\n");
      out.write("    background: darkgoldenrod;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  .orbit-slide:nth-of-type(4) & {\n");
      out.write("    background: lightseagreen;\n");
      out.write("  }\n");
      out.write("}\n");
      out.write("h2 { text-align:center; }\n");
      out.write("\n");
      out.write(".mBan span {\n");
      out.write("    display: block;\n");
      out.write("}\n");
      out.write(".mBan ul {\n");
      out.write("    display: flex;\n");
      out.write("    justify-content: space-between;\n");
      out.write("    align-items: flex-end;\n");
      out.write("    text-align: center;\n");
      out.write("    margin: 30px 0 55px;\n");
      out.write("}\n");
      out.write(".wrap {\n");
      out.write("    position: relative;\n");
      out.write("    max-width: 1280px;\n");
      out.write("    margin: 0 auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".quick {\n");
      out.write("    position: fixed;\n");
      out.write("    right: 5%;\n");
      out.write("    top: 247px;\n");
      out.write("    text-align: center;\n");
      out.write("    border-radius: 20px;\n");
      out.write("    background: #fff;\n");
      out.write("    box-shadow: 0 0 10px rgb(0 0 0 / 30%);\n");
      out.write("    z-index: 50;\n");
      out.write("    overflow: hidden;\n");
      out.write("}\n");
      out.write(".quick_toggle {\n");
      out.write("    padding: 15px 0;\n");
      out.write("    color: #fff;\n");
      out.write("    background: #002242;\n");
      out.write("}\n");
      out.write(".quick .top_btn {\n");
      out.write("    display: block;\n");
      out.write("    width: 51px;\n");
      out.write("    height: 51px;\n");
      out.write("    margin: 15px 20px;\n");
      out.write("    padding: 10px 5px !important;\n");
      out.write("    font-size: 1.2rem;\n");
      out.write("    border-top: 0;\n");
      out.write("    border-radius: 50%;\n");
      out.write("    background: #f5f5f5;\n");
      out.write("}	\n");
      out.write("\n");
      out.write(".wrap>li {\n");
      out.write("    float: left;\n");
      out.write("    width: 48%;\n");
      out.write("}\n");
      out.write(".contact a {\n");
      out.write("    display: block;\n");
      out.write("    text-align: center;\n");
      out.write("    height: 75px;\n");
      out.write("    line-height: 75px;\n");
      out.write("    font-family: 'S-CoreDream-5Medium';\n");
      out.write("    color: #fff;\n");
      out.write("    font-size: 2.1rem;\n");
      out.write("    border-radius: 75px;\n");
      out.write("    max-width: 300px;\n");
      out.write("}\n");
      out.write(".contact a.l1{\n");
      out.write("    background: #0092a2;\n");
      out.write("}\n");
      out.write(".contact a.l2 {\n");
      out.write("    background: #003e67;\n");
      out.write("}\n");
      out.write(".contact a:hover span {\n");
      out.write("    padding-left: 60px;\n");
      out.write("}\n");
      out.write(".contact a span {\n");
      out.write("    display: inline-block;\n");
      out.write("    padding-left: 20px;\n");
      out.write("    transition: .5s;\n");
      out.write("}\n");
      out.write("\n");
      out.write("*, *:before, *:after {\n");
      out.write("    box-sizing: border-box;\n");
      out.write("    word-wrap: break-word;\n");
      out.write("    word-break: keep-all;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".col_con {\n");
      out.write("    width: 100%;\n");
      out.write("}\n");
      out.write(".pzone2_list {\n");
      out.write("    display: flex;\n");
      out.write("    align-items: center;\n");
      out.write("    flex-direction: row;\n");
      out.write("}\n");
      out.write(".pzone2_list>li {\n");
      out.write("    width: 27%;\n");
      out.write("    display: flex;\n");
      out.write("    flex-direction: row;\n");
      out.write("    justify-content: flex-end;\n");
      out.write("}\n");
      out.write(".pzone2_list>li>a img {\n");
      out.write("    transition: .5s;\n");
      out.write("    border-radius: 20px;\n");
      out.write("    vertical-align: initial;\n");
      out.write("}\n");
      out.write("a {\n");
      out.write("    color: #000;\n");
      out.write("    text-decoration: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("#page2 { background-color: rgba(230, 248, 255, 0.5); }\n");
      out.write(".pic_lst { clear:both; width: 130%; padding-bottom: 80px; }\n");
      out.write(".pic_lst:after { content:\"\"; display:block; clear:both; }\n");
      out.write(".pic_lst li { float:left; position:relative; margin-bottom: 40px; }\n");
      out.write(".pic_lst li a { display:block; width: 360px; margin-right: 40px;overflow: hidden; height: 300px; }\n");
      out.write(".pic_lst li a img { display:block; width:600px; /* margin-left: -120px; */ transition-duration:0.8s; }\n");
      out.write(".pic_lst li a:hover img { margin-left: 0; }\n");
      out.write(".pic_lst li a .hv_box { width: 360px; height: 300px; color:#fff; opacity:0; position:absolute; top:0; left: 0;\n");
      out.write("                            z-index:10; transition-duration:0.8s; background-color:transparent; }\n");
      out.write(".pic_lst li a:hover .hv_box { opacity:1; }\n");
      out.write(".pic_tit { position:absolute; top:30px; left: 30px; text-shadow:0px 0px 3px red; }\n");
      out.write(".pic_com { position:absolute; right:30px; bottom:30px; text-shadow:0px 0px 3px blue; }\n");
      out.write(".page { clear:both; width: 100%; }\n");
      out.write(".page_wrap { width: 1200px; margin: 0 auto; }\n");
      out.write("#page1, #page3 { background-color:#ececec; }\n");
      out.write(".page_tit { text-align: center; font-size:32px; padding-top:1.2em; padding-bottom: 0.8em; }\n");
      out.write(".lst { clear:both; width: 1200px; }\n");
      out.write(".lst:after { content:\"\"; display:block; clear: both;}\n");
      out.write(".lst li { margin-bottom: 40px; }\n");
      out.write(".lst li.left { float:left; width: 816px; height: 459px;}\n");
      out.write(".lst li.right { float:right; width:350px; height: 459px; }\n");
      out.write(".ico_lst { clear:both; width: 100%; overflow:hidden; }\n");
      out.write(".ico_lst li a { display:block; background-repeat: no-repeat; background-position:0px center; background-size:auto 80%; padding-left: 55px; }\n");
      out.write(".cate_tit { color:#222; font-size:20px; padding-bottom: 0.5em; }\n");
      out.write(".cate_com { color:#222; font-size:14px; overflow:hidden; white-space:nowrap; text-overflow:ellipsis; }\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./include/header.jsp", out, false);
      out.write("\n");
      out.write("	<div class=\"row\" style=\"margin-bottom:100px;\">\n");
      out.write("	  <div class=\"columns\">\n");
      out.write("	    <div class=\"orbit\" role=\"region\" aria-label=\"Favorite Space Pictures\" data-orbit>\n");
      out.write("	      <ul class=\"orbit-container\">\n");
      out.write("	        <button class=\"orbit-previous\"><span class=\"show-for-sr\">Previous Slide</span>&#9664;&#xFE0E;</button>\n");
      out.write("	        <button class=\"orbit-next\"><span class=\"show-for-sr\">Next Slide</span>&#9654;&#xFE0E;</button>\n");
      out.write("	        <li class=\"is-active orbit-slide\">\n");
      out.write("	          <img class=\"orbit-image\" src=\"https://www.ottogi.co.kr/images/main/img_visual51.jpg\" alt=\"Space\">\n");
      out.write("	          <figcaption class=\"orbit-caption\">Space, the final frontier.</figcaption>\n");
      out.write("	        </li>\n");
      out.write("	        <li class=\"orbit-slide\">\n");
      out.write("	          <img class=\"orbit-image\" src=\"https://www.ottogi.co.kr/images/main/img_visual52.jpg\" alt=\"Space\">\n");
      out.write("	          <figcaption class=\"orbit-caption\">Lets Rocket!</figcaption>\n");
      out.write("	        </li>\n");
      out.write(" 	        <li class=\"orbit-slide\">\n");
      out.write("	          <img class=\"orbit-image\" src=\"https://www.ottogi.co.kr/images/main/img_visual53.jpg\" alt=\"Space\">\n");
      out.write("	          <figcaption class=\"orbit-caption\">Encapsulating</figcaption>\n");
      out.write("	        </li>\n");
      out.write("	        <li class=\"orbit-slide\">\n");
      out.write("	          <img class=\"orbit-image\" src=\"https://www.ottogi.co.kr/images/main/img_visual50.jpg\" alt=\"Space\">\n");
      out.write("	          <figcaption class=\"orbit-caption\">Outta This World</figcaption>\n");
      out.write("	        </li>\n");
      out.write("	        <li class=\"orbit-slide\">\n");
      out.write("	          <img class=\"orbit-image\" src=\"https://www.ottogi.co.kr/images/main/img_visual47.jpg\" alt=\"Space\">\n");
      out.write("	          <figcaption class=\"orbit-caption\">Outta This World</figcaption>\n");
      out.write("	        </li>\n");
      out.write("	        <li class=\"orbit-slide\">\n");
      out.write("	          <img class=\"orbit-image\" src=\"https://www.ottogi.co.kr/images/main/img_visual41.jpg\" alt=\"Space\">\n");
      out.write("	          <figcaption class=\"orbit-caption\">Outta This World</figcaption>\n");
      out.write("	        </li>\n");
      out.write("	      </ul>\n");
      out.write("	      <nav class=\"orbit-bullets\">\n");
      out.write("	        <button class=\"is-active\" data-slide=\"0\"><span class=\"show-for-sr\">First slide details.</span><span class=\"show-for-sr\">Current Slide</span></button>\n");
      out.write("	        <button data-slide=\"1\"><span class=\"show-for-sr\">Second slide details.</span></button>\n");
      out.write("	        <button data-slide=\"2\"><span class=\"show-for-sr\">Second slide details.</span></button>\n");
      out.write("	        <button data-slide=\"3\"><span class=\"show-for-sr\">Second slide details.</span></button>\n");
      out.write("	        <button data-slide=\"4\"><span class=\"show-for-sr\">Second slide details.</span></button>\n");
      out.write("	        <button data-slide=\"5\"><span class=\"show-for-sr\">Second slide details.</span></button>\n");
      out.write("	      </nav>\n");
      out.write("	    </div>\n");
      out.write("	  </div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("<div class=\"wrap\" style=\"margin-bottom:500px;\">\n");
      out.write("<section class=\"page\" id=\"page2\" style=\"background-color:#fef100;\">\n");
      out.write("    <div class=\"page_wrap\">\n");
      out.write("        <h1 class=\"page_tit\" style=\"color:black; font-weight:bolder;\">오뚜기 인기상품<br></h1>\n");
      out.write("		<h5 class=\"page_tit\" style=\"color:black; font-weight:bolder;\">오뚜기의 인기상품들을 소개 합니다.</h5>\n");
      out.write("        <ul class=\"pic_lst\">\n");
      out.write("            <li>\n");
      out.write("                <a href=\"\">\n");
      out.write("                    <img src=\"https://www.ottogi.co.kr/pds/product/2021-04-20_671244888[7].jpg\" alt=\"\" class=\"pic\">\n");
      out.write("                    <div class=\"hv_box\">\n");
      out.write("                        <h3 class=\"pic_tit\">프레스코 미트 스파게티소스</h3>\n");
      out.write("                        <p class=\"pic_com\">진한 풍미 가득한 미트 스파게티소스</p>\n");
      out.write("                    </div>\n");
      out.write("                </a>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"\">\n");
      out.write("                    <img src=\"https://www.ottogi.co.kr/pds/product/2022-03-17_367582465[3].jpg\" alt=\"OLED로 만들어낸 미래도시\" class=\"pic\">\n");
      out.write("                    <div class=\"hv_box\">\n");
      out.write("                        <h3 class=\"pic_tit\">시그니처익스트림_콘크러스트_피자 530G</h3>\n");
      out.write("                        <p class=\"pic_com\">킬바사 소시지와 불고기가 듬뿍!</p>\n");
      out.write("                    </div>\n");
      out.write("                </a>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"\">\n");
      out.write("                    <img src=\"https://www.ottogi.co.kr/pds/product/2021-06-24_391242475[1].jpg\" alt=\"OLED Shelf, 2022 레드닷 디자인 어워드 디자인 컨셉 부문 Winner 수상\" class=\"pic\">\n");
      out.write("                    <div class=\"hv_box\">\n");
      out.write("                        <h3 class=\"pic_tit\">오즈키친 게살크래미주먹밥</h3>\n");
      out.write("                        <p class=\"pic_com\">게살크래미와 스크램블에그가 듬뿍!</p>\n");
      out.write("                    </div>\n");
      out.write("                </a>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"\">\n");
      out.write("                    <img src=\"https://www.ottogi.co.kr/pds/product/2020-03-18_82503302[5].jpg\" alt=\"제 2회 OLEDs Go!\" class=\"pic\">\n");
      out.write("                    <div class=\"hv_box\">\n");
      out.write("                        <h3 class=\"pic_tit\">뚜기네 분식집 라볶이</h3>\n");
      out.write("                        <p class=\"pic_com\">매콤한 소스에 오뚜기 라면사리와 쌀떡이 쏙!</p>\n");
      out.write("                    </div>\n");
      out.write("                </a>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"\">\n");
      out.write("                    <img src=\"https://www.ottogi.co.kr/pds/product/2022-02-03_327063180[1].jpg\" alt=\"투명 OLED로 변화하는 오피스 인테리어\" class=\"pic\">\n");
      out.write("                    <div class=\"hv_box\">\n");
      out.write("                        <h3 class=\"pic_tit\">오늘밥상 제육볶음양념</h3>\n");
      out.write("                        <p class=\"pic_com\">한국인의 No.1 소울푸드!!</p>\n");
      out.write("                    </div>\n");
      out.write("                </a>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"\">\n");
      out.write("                    <img src=\"https://www.ottogi.co.kr/pds/product/2022-02-03_327063180[3].jpg\" alt=\"오늘밥상 춘천식 철판닭갈비양념\" class=\"pic\">\n");
      out.write("                    <div class=\"hv_box\">\n");
      out.write("                        <h3 class=\"pic_tit\">오늘밥상 춘천식 철판닭갈비양념</h3>\n");
      out.write("                        <p class=\"pic_com\">정통 춘천닭갈비의 매콤한 맛 그대로!</p>\n");
      out.write("                    </div>\n");
      out.write("                </a>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"\">\n");
      out.write("                    <img src=\"https://www.ottogi.co.kr/pds/product/2020-03-18_82503302[5].jpg\" alt=\"제 2회 OLEDs Go!\" class=\"pic\">\n");
      out.write("                    <div class=\"hv_box\">\n");
      out.write("                        <h3 class=\"pic_tit\">뚜기네 분식집 라볶이</h3>\n");
      out.write("                        <p class=\"pic_com\">매콤한 소스에 오뚜기 라면사리와 쌀떡이 쏙!</p>\n");
      out.write("                    </div>\n");
      out.write("                </a>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"\">\n");
      out.write("                    <img src=\"https://www.ottogi.co.kr/pds/product/2020-10-07_526529153[3].jpg\" alt=\"투명 OLED로 변화하는 오피스 인테리어\" class=\"pic\">\n");
      out.write("                    <div class=\"hv_box\">\n");
      out.write("                        <h3 class=\"pic_tit\">중국식 18mm 넓은 당면</h3>\n");
      out.write("                        <p class=\"pic_com\">바로 삶아 먹는 쫄깃한 중국당면</p>\n");
      out.write("                    </div>\n");
      out.write("                </a>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"\">\n");
      out.write("                    <img src=\"https://www.ottogi.co.kr/pds/product/jun_l1.jpg\" alt=\"미래형 매장의 시작\" class=\"pic\">\n");
      out.write("                    <div class=\"hv_box\">\n");
      out.write("                        <h3 class=\"pic_tit\">전복죽</h3>\n");
      out.write("                        <p class=\"pic_com\">야채가 들어있어 맛이 조화로운 전복죽</p>\n");
      out.write("                    </div>\n");
      out.write("                </a>\n");
      out.write("            </li>\n");
      out.write("        </ul>\n");
      out.write("    </div>\n");
      out.write(" </section>\n");
      out.write(" <br><hr><br>\n");
      out.write(" <section class=\"page\" id=\"page3\" style=\"margin-top:100px;\">\n");
      out.write(" 	<h1 style=\"text-align:center; background-color:white;\">이벤트  신제품 소개</h1>\n");
      out.write("    <div class=\"row\" style=\"width:500px; height:300px; float:right; margin-left:700px; position:absolute; margin-top: 80px;\">\n");
      out.write("	  <div class=\"columns\">\n");
      out.write("	    <div class=\"orbit\" role=\"region\" aria-label=\"Favorite Space Pictures\" data-orbit>\n");
      out.write("	      <ul class=\"orbit-container\">\n");
      out.write("	        <button class=\"orbit-previous\"><span class=\"show-for-sr\">Previous Slide</span>&#9664;&#xFE0E;</button>\n");
      out.write("	        <button class=\"orbit-next\"><span class=\"show-for-sr\">Next Slide</span>&#9654;&#xFE0E;</button>\n");
      out.write("	        <li class=\"is-active orbit-slide\">\n");
      out.write("	          <img class=\"orbit-image\" src=\"https://www.ottogi.co.kr/pds/upfile/2021-05-27_805369006[5].jpg\" alt=\"Space\">\n");
      out.write("	          <figcaption class=\"orbit-caption\">이벤트</figcaption>\n");
      out.write("	        </li>\n");
      out.write("	        <li class=\"orbit-slide\">\n");
      out.write("	          <img class=\"orbit-image\" src=\"https://www.ottogi.co.kr/pds/upfile/2022-10-28_417285700.jpg\" alt=\"Space\">\n");
      out.write("	          <figcaption class=\"orbit-caption\">이벤트</figcaption>\n");
      out.write("	        </li>\n");
      out.write("	        <li class=\"orbit-slide\">\n");
      out.write("	          <img class=\"orbit-image\" src=\"https://www.ottogi.co.kr/pds/upfile/2022-11-03_267296674.jpg\" alt=\"Space\">\n");
      out.write("	          <figcaption class=\"orbit-caption\">이벤트</figcaption>\n");
      out.write("	        </li>\n");
      out.write("	      </ul>\n");
      out.write("	      <nav class=\"orbit-bullets\">\n");
      out.write("	        <button class=\"is-active\" data-slide=\"0\"><span class=\"show-for-sr\">First slide details.</span><span class=\"show-for-sr\">Current Slide</span></button>\n");
      out.write("	        <button data-slide=\"1\"><span class=\"show-for-sr\">Second slide details.</span></button>\n");
      out.write("	        <button data-slide=\"2\"><span class=\"show-for-sr\">Third slide details.</span></button>\n");
      out.write("	      </nav>\n");
      out.write("	    </div>\n");
      out.write("	  </div>\n");
      out.write("	</div>\n");
      out.write("	\n");
      out.write("	<div class=\"row\" style=\"width:300px; height:300px; float:left; margin-left:100px; position:absolute; margin-top: 50px;\">\n");
      out.write("	  <div class=\"columns\">\n");
      out.write("	    <div class=\"orbit\" role=\"region\" aria-label=\"Favorite Space Pictures\" data-orbit>\n");
      out.write("	      <ul class=\"orbit-container\">\n");
      out.write("	        <button class=\"orbit-previous\"><span class=\"show-for-sr\">Previous Slide</span>&#9664;&#xFE0E;</button>\n");
      out.write("	        <button class=\"orbit-next\"><span class=\"show-for-sr\">Next Slide</span>&#9654;&#xFE0E;</button>\n");
      out.write("	        <li class=\"is-active orbit-slide\" >\n");
      out.write("	          <img class=\"orbit-image\" src=\"	https://www.ottogi.co.kr/pds/upfile/2022-10-13_858980330[1].jpg\" alt=\"Space\">\n");
      out.write("	          <figcaption class=\"orbit-caption\">신제품 소개</figcaption>\n");
      out.write("	        </li>\n");
      out.write("	        <li class=\"orbit-slide\">\n");
      out.write("	          <img class=\"orbit-image\" src=\"https://www.ottogi.co.kr/pds/upfile/2022-10-13_858980330[2].jpg\" alt=\"Space\">\n");
      out.write("	          <figcaption class=\"orbit-caption\">신제품 소개</figcaption>\n");
      out.write("	        </li>\n");
      out.write("	        <li class=\"orbit-slide\">\n");
      out.write("	          <img class=\"orbit-image\" src=\"https://www.ottogi.co.kr/pds/upfile/2022-10-13_858980330.jpg\" alt=\"Space\">\n");
      out.write("	          <figcaption class=\"orbit-caption\">신제품 소개</figcaption>\n");
      out.write("	        </li>\n");
      out.write("	      </ul>\n");
      out.write("	      <nav class=\"orbit-bullets\">\n");
      out.write("	        <button class=\"is-active\" data-slide=\"0\"><span class=\"show-for-sr\">First slide details.</span><span class=\"show-for-sr\">Current Slide</span></button>\n");
      out.write("	        <button data-slide=\"1\"><span class=\"show-for-sr\">Second slide details.</span></button>\n");
      out.write("	        <button data-slide=\"2\"><span class=\"show-for-sr\">Third slide details.</span></button>\n");
      out.write("	      </nav>\n");
      out.write("	    </div>\n");
      out.write("	  </div>\n");
      out.write("	</div>\n");
      out.write("  </section>   \n");
      out.write("</div>\n");
      out.write("<footer id=\"footer\" class=\"footer-nav row expanded collapse\" >\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./include/footer.jsp", out, false);
      out.write("\n");
      out.write("</footer>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/home.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path1");
      // /WEB-INF/views/home.jsp(6,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/home.jsp(6,0) '${request.getContextPath() }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${request.getContextPath() }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
